# Generated by Django 3.2.7 on 2021-11-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_of_class', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_students_to_students',
            name='attendance',
            field=models.ManyToManyField(to='session_of_class.Session'),
        ),
    ]
