# Generated by Django 3.2.7 on 2021-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('price', models.CharField(default='', max_length=15)),
                ('description', models.TextField(default='')),
                ('number_sessions', models.PositiveIntegerField(default=20)),
                ('description_image', models.ImageField(upload_to='static/image/description_course')),
            ],
        ),
    ]
